In [6]:
# Load the paediatric data :AIOLOS19-12-2023
import pandas as pd
import numpy as np

# Load the data in xlsx file 
df = pd.read_excel('../data/01_raw/AIOLOS19-12-2023.xlsx', skiprows=1, header=[0, 1])
# Remove the first row called "semaine"
df = df.drop(df.index[0])
df

    Unnamed: 0_level_0   Bronchiolites                     Covid               \
    Unnamed: 0_level_1 TDR indéterminé   TDR+  TDR-  Total  TDR+  TDR-  Total
1             2017-w26            22.0    NaN   NaN   22.0   NaN   NaN    NaN
2             2017-w27            20.0    NaN   NaN   20.0   NaN   NaN    NaN
3             2017-w28            18.0    NaN   NaN   18.0   NaN   NaN    NaN
4             2017-w29            11.0    NaN   NaN   11.0   NaN   NaN    NaN
5             2017-w30            13.0    NaN   NaN   13.0   NaN   NaN    NaN
..                 ...             ...    ...   ...    ...   ...   ...    ...
334           2023-w46           141.0  119.0  67.0  327.0  27.0  51.0   78.0
335           2023-w47           143.0  141.0  58.0  342.0  54.0  49.0  103.0
336           2023-w48           153.0  135.0  61.0  349.0  38.0  49.0   87.0
337           2023-w49           129.0   98.0  51.0  278.0  58.0  49.0  107.0
338           2023-w50           132.0   73.0  50.0  255.0  50.0  49.0   99.0

             Grippe                    Pneumopathie Total Synd. resp.  \
    TDR indéterminé  TDR+  TDR-  Total        Total                 n
1               NaN   NaN   NaN    NaN          3.0              25.0
2               NaN   NaN   NaN    NaN          6.0              26.0
3               NaN   NaN   NaN    NaN          2.0              20.0
4               NaN   NaN   NaN    NaN          2.0              13.0
5               NaN   NaN   NaN    NaN          5.0              18.0
..              ...   ...   ...    ...          ...               ...
334            35.0  10.0  55.0  100.0         31.0             536.0
335            48.0  17.0  46.0  111.0         38.0             594.0
336            49.0  23.0  45.0  117.0         59.0             612.0
337            46.0  71.0  52.0  169.0         68.0             622.0
338            44.0  80.0  58.0  182.0         54.0             590.0

                Nb consultations
    % / Nb cons            Total
1           0.2            12958
2           0.2            12677
3           0.2             9430
4           0.1            10774
5           0.2             9297
..          ...              ...
334         4.6            11674
335         5.3            11191
336         5.3            11464
337         5.6            11114
338         5.4            10841

[338 rows x 16 columns]

In [5]:
# Load the paediatric data :AIOLOS19-12-2023
import pandas as pd
import numpy as np

# Load the data in xlsx file 
df = pd.read_csv('../data/01_raw/AIOLOS19-12-2023.csv', skiprows=0, header=[0, 1], encoding = "latin1")
# Remove the first row called "semaine"
df = df.drop(df.index[0])
df

,Unnamed: 0_level_0,Bronchiolites,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Covid,Unnamed: 6_level_0,Unnamed: 7_level_0,Grippe,Unnamed: 9_level_0,Unnamed: 10_level_0,Unnamed: 11_level_0,Pneumopathie,Total Synd. resp.,Unnamed: 14_level_0,Nb consultations
,Unnamed: 0_level_1,TDR indéterminé,TDR+,TDR-,Total,TDR+,TDR-,Total,TDR indéterminé,TDR+,TDR-,Total,Total,n,% / Nb cons,Total
1,2017-w26,22.0,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,25.0,0.2,12958
2,2017-w27,20.0,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,26.0,0.2,12677
3,2017-w28,18.0,NaN,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,20.0,0.2,9430
4,2017-w29,11.0,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,13.0,0.1,10774
5,2017-w30,13.0,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,18.0,0.2,9297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,2023-w46,141.0,119.0,67.0,327.0,27.0,51.0,78.0,35.0,10.0,55.0,100.0,31.0,536.0,4.6,11674
335,2023-w47,143.0,141.0,58.0,342.0,54.0,49.0,103.0,48.0,17.0,46.0,111.0,38.0,594.0,5.3,11191
336,2023-w48,153.0,135.0,61.0,349.0,38.0,49.0,87.0,49.0,23.0,45.0,117.0,59.0,612.0,5.3,11464
337,2023-w49,129.0,98.0,51.0,278.0,58.0,49.0,107.0,46.0,71.0,52.0,169.0,68.0,622.0,5.6,11114
338,2023-w50,132.0,73.0,50.0,255.0,50.0,49.0,99.0,44.0,80.0,58.0,182.0,54.0,590.0,5.4,10841

In [8]:
from typing import Any, Dict

import pandas as pd
from kedro.io.core import PROTOCOL_DELIMITER, Version
from kedro_datasets.pandas import CSVDataSet, ExcelDataSet

class SFTPExcelDataSet(ExcelDataSet):
    def __init__(
        self,
        filepath: str,
        load_args: Dict[str, Any] = None,
        save_args: Dict[str, Any] = None,
        version: Version = None,
        credentials: Dict[str, Any] = None,
        fs_args: Dict[str, Any] = None,
        metadata: Dict[str, Any] = None,
    ) -> None:
        print("Filepath: ...")
        print(filepath)

        super().__init__(
            filepath, load_args, save_args, version, credentials, fs_args, metadata
        )

    def _load(self) -> pd.DataFrame:
        load_path = str(self._get_load_path())

        print("Loading path: ...")
        print(load_path)
        if self._protocol == "file":
            # file:// protocol seems to misbehave on Windows
            # (<urlopen error file not on local host>),
            # so we don't join that back to the filepath;
            # storage_options also don't work with local paths
            return pd.read_excel(
                load_path, skiprows=1, header=[0, 1], **self._load_args
            )

        load_path = f"{self._protocol}{PROTOCOL_DELIMITER}{load_path}"

        sftp = self._fs

        with sftp.open(load_path) as f: 
            data = pd.read_excel(f, skiprows=1, header=[0, 1], **self._load_args)
        return data


test_ds = SFTPExcelDataSet()

TypeError: SFTPExcelDataSet.__init__() missing 1 required positional argument: 'filepath'

In [1139]:
# Replace all NaN values by 0
df = df.replace(np.nan, 0)

# Replace cells containing "?" by NaN   
df = df.replace('?', np.nan)

In [1140]:
# Rename the first columns to correspond to the date, rename "Grippe" to "Flu", "Pneumopathie" tp "Pneumopathy" and "Bronchiolite" to "Bronchiolitis" 

df.rename(columns={'Unnamed: 0_level_0': 'Date','Unnamed: 0_level_1': 'Date', 'Grippe': 'Flu', 'Pneumopathie': 'Pneumopathy', 'Bronchiolites': 'Bronchiolitis', 'Total Synd. resp.': "Total Resp. Synd.", "Nb consultations":"Number of consultations", "TDR indéterminé": "Undetermined Rapid Diagnostic Test", "% / Nb cons":"% of consulations", "TDR+": "Rapid Diagnostic Test +", "TDR-": "Rapid Diagnostic Test -",'Total': 'current', 'n':'current' }, inplace=True)
df

         Date                      Bronchiolitis                          \
         Date Undetermined Rapid Diagnostic Test Rapid Diagnostic Test +
1    2017-w26                               22.0                     0.0
2    2017-w27                               20.0                     0.0
3    2017-w28                               18.0                     0.0
4    2017-w29                               11.0                     0.0
5    2017-w30                               13.0                     0.0
..        ...                                ...                     ...
334  2023-w46                              141.0                   119.0
335  2023-w47                              143.0                   141.0
336  2023-w48                              153.0                   135.0
337  2023-w49                              129.0                    98.0
338  2023-w50                              132.0                    73.0

                                                      Covid  \
    Rapid Diagnostic Test - current Rapid Diagnostic Test +
1                       0.0    22.0                     0.0
2                       0.0    20.0                     0.0
3                       0.0    18.0                     0.0
4                       0.0    11.0                     0.0
5                       0.0    13.0                     0.0
..                      ...     ...                     ...
334                    67.0   327.0                    27.0
335                    58.0   342.0                    54.0
336                    61.0   349.0                    38.0
337                    51.0   278.0                    58.0
338                    50.0   255.0                    50.0

                                                                   Flu  \
    Rapid Diagnostic Test - current Undetermined Rapid Diagnostic Test
1                       0.0     0.0                                0.0
2                       0.0     0.0                                0.0
3                       0.0     0.0                                0.0
4                       0.0     0.0                                0.0
5                       0.0     0.0                                0.0
..                      ...     ...                                ...
334                    51.0    78.0                               35.0
335                    49.0   103.0                               48.0
336                    49.0    87.0                               49.0
337                    49.0   107.0                               46.0
338                    49.0    99.0                               44.0

                                                            Pneumopathy  \
    Rapid Diagnostic Test + Rapid Diagnostic Test - current     current
1                       0.0                     0.0     0.0         3.0
2                       0.0                     0.0     0.0         6.0
3                       0.0                     0.0     0.0         2.0
4                       0.0                     0.0     0.0         2.0
5                       0.0                     0.0     0.0         5.0
..                      ...                     ...     ...         ...
334                    10.0                    55.0   100.0        31.0
335                    17.0                    46.0   111.0        38.0
336                    23.0                    45.0   117.0        59.0
337                    71.0                    52.0   169.0        68.0
338                    80.0                    58.0   182.0        54.0

    Total Resp. Synd.                   Number of consultations
              current % of consulations                 current
1                25.0               0.2                 12958.0
2                26.0               0.2                 12677.0
3                20.0               0.2                  9430.0
4                13.0               0.1                 10774.0
5                18.0               0.2                  9297.0
..                ...               ...                     ...
334             536.0               4.6                 11674.0
335             594.0               5.3                 11191.0
336             612.0               5.3                 11464.0
337             622.0               5.6                 11114.0
338             590.0               5.4                 10841.0

[338 rows x 16 columns]

In [1141]:
week_year = df[('Date', 'Date')].str.split('-w', expand=True)

df['Week'] = week_year[1].astype(int)
df['Year'] = week_year[0].astype(int)
df.drop(('Date', 'Date'), axis=1, inplace=True)

In [1142]:
# Remove week 53
df = df.loc[df[('Week')] != 53]
# Change all data types to int except for the date
df = df.astype({"Flu": int, "Bronchiolitis":int, "Pneumopathy": int, "Total Resp. Synd.": int, "Covid" : int})

In [1143]:
df.set_index(['Year', 'Week'], inplace=True)

In [1144]:
df

                               Bronchiolitis                          \
          Undetermined Rapid Diagnostic Test Rapid Diagnostic Test +
Year Week
2017 26                                 22.0                     0.0
     27                                 20.0                     0.0
     28                                 18.0                     0.0
     29                                 11.0                     0.0
     30                                 13.0                     0.0
...                                      ...                     ...
2023 46                                141.0                   119.0
     47                                143.0                   141.0
     48                                153.0                   135.0
     49                                129.0                    98.0
     50                                132.0                    73.0

                                                            Covid  \
          Rapid Diagnostic Test - current Rapid Diagnostic Test +
Year Week
2017 26                       0.0    22.0                     0.0
     27                       0.0    20.0                     0.0
     28                       0.0    18.0                     0.0
     29                       0.0    11.0                     0.0
     30                       0.0    13.0                     0.0
...                           ...     ...                     ...
2023 46                      67.0   327.0                    27.0
     47                      58.0   342.0                    54.0
     48                      61.0   349.0                    38.0
     49                      51.0   278.0                    58.0
     50                      50.0   255.0                    50.0

                                                                         Flu  \
          Rapid Diagnostic Test - current Undetermined Rapid Diagnostic Test
Year Week
2017 26                       0.0     0.0                                0.0
     27                       0.0     0.0                                0.0
     28                       0.0     0.0                                0.0
     29                       0.0     0.0                                0.0
     30                       0.0     0.0                                0.0
...                           ...     ...                                ...
2023 46                      51.0    78.0                               35.0
     47                      49.0   103.0                               48.0
     48                      49.0    87.0                               49.0
     49                      49.0   107.0                               46.0
     50                      49.0    99.0                               44.0

                                                                  Pneumopathy  \
          Rapid Diagnostic Test + Rapid Diagnostic Test - current     current
Year Week
2017 26                       0.0                     0.0     0.0         3.0
     27                       0.0                     0.0     0.0         6.0
     28                       0.0                     0.0     0.0         2.0
     29                       0.0                     0.0     0.0         2.0
     30                       0.0                     0.0     0.0         5.0
...                           ...                     ...     ...         ...
2023 46                      10.0                    55.0   100.0        31.0
     47                      17.0                    46.0   111.0        38.0
     48                      23.0                    45.0   117.0        59.0
     49                      71.0                    52.0   169.0        68.0
     50                      80.0                    58.0   182.0        54.0

          Total Resp. Synd.                   Number of consultations
                    current % of consulations                 current
Year Week
2017 26                25.0               0.2                 12958.0
     27                26.0               0.2                 12677.0
     28                20.0               0.2                  9430.0
     29                13.0               0.1                 10774.0
     30                18.0               0.2                  9297.0
...                     ...               ...                     ...
2023 46               536.0               4.6                 11674.0
     47               594.0               5.3                 11191.0
     48               612.0               5.3                 11464.0
     49               622.0               5.6                 11114.0
     50               590.0               5.4                 10841.0

[337 rows x 15 columns]

In [1145]:
df

                               Bronchiolitis                          \
          Undetermined Rapid Diagnostic Test Rapid Diagnostic Test +
Year Week
2017 26                                 22.0                     0.0
     27                                 20.0                     0.0
     28                                 18.0                     0.0
     29                                 11.0                     0.0
     30                                 13.0                     0.0
...                                      ...                     ...
2023 46                                141.0                   119.0
     47                                143.0                   141.0
     48                                153.0                   135.0
     49                                129.0                    98.0
     50                                132.0                    73.0

                                                            Covid  \
          Rapid Diagnostic Test - current Rapid Diagnostic Test +
Year Week
2017 26                       0.0    22.0                     0.0
     27                       0.0    20.0                     0.0
     28                       0.0    18.0                     0.0
     29                       0.0    11.0                     0.0
     30                       0.0    13.0                     0.0
...                           ...     ...                     ...
2023 46                      67.0   327.0                    27.0
     47                      58.0   342.0                    54.0
     48                      61.0   349.0                    38.0
     49                      51.0   278.0                    58.0
     50                      50.0   255.0                    50.0

                                                                         Flu  \
          Rapid Diagnostic Test - current Undetermined Rapid Diagnostic Test
Year Week
2017 26                       0.0     0.0                                0.0
     27                       0.0     0.0                                0.0
     28                       0.0     0.0                                0.0
     29                       0.0     0.0                                0.0
     30                       0.0     0.0                                0.0
...                           ...     ...                                ...
2023 46                      51.0    78.0                               35.0
     47                      49.0   103.0                               48.0
     48                      49.0    87.0                               49.0
     49                      49.0   107.0                               46.0
     50                      49.0    99.0                               44.0

                                                                  Pneumopathy  \
          Rapid Diagnostic Test + Rapid Diagnostic Test - current     current
Year Week
2017 26                       0.0                     0.0     0.0         3.0
     27                       0.0                     0.0     0.0         6.0
     28                       0.0                     0.0     0.0         2.0
     29                       0.0                     0.0     0.0         2.0
     30                       0.0                     0.0     0.0         5.0
...                           ...                     ...     ...         ...
2023 46                      10.0                    55.0   100.0        31.0
     47                      17.0                    46.0   111.0        38.0
     48                      23.0                    45.0   117.0        59.0
     49                      71.0                    52.0   169.0        68.0
     50                      80.0                    58.0   182.0        54.0

          Total Resp. Synd.                   Number of consultations
                    current % of consulations                 current
Year Week
2017 26                25.0               0.2                 12958.0
     27                26.0               0.2                 12677.0
     28                20.0               0.2                  9430.0
     29                13.0               0.1                 10774.0
     30                18.0               0.2                  9297.0
...                     ...               ...                     ...
2023 46               536.0               4.6                 11674.0
     47               594.0               5.3                 11191.0
     48               612.0               5.3                 11464.0
     49               622.0               5.6                 11114.0
     50               590.0               5.4                 10841.0

[337 rows x 15 columns]

In [1146]:
# Select only The Total Subcolumns Columns

df= df.loc[:, [('Covid', 'current'), ('Flu',  'current'), ('Bronchiolitis', 'current'), ('Pneumopathy', 'current'), ('Total Resp. Synd.', 'current'), ('Number of consultations', 'current')]]
df

            Covid     Flu Bronchiolitis Pneumopathy Total Resp. Synd.  \
          current current       current     current           current
Year Week
2017 26       0.0     0.0          22.0         3.0              25.0
     27       0.0     0.0          20.0         6.0              26.0
     28       0.0     0.0          18.0         2.0              20.0
     29       0.0     0.0          11.0         2.0              13.0
     30       0.0     0.0          13.0         5.0              18.0
...           ...     ...           ...         ...               ...
2023 46      78.0   100.0         327.0        31.0             536.0
     47     103.0   111.0         342.0        38.0             594.0
     48      87.0   117.0         349.0        59.0             612.0
     49     107.0   169.0         278.0        68.0             622.0
     50      99.0   182.0         255.0        54.0             590.0

          Number of consultations
                          current
Year Week
2017 26                   12958.0
     27                   12677.0
     28                    9430.0
     29                   10774.0
     30                    9297.0
...                           ...
2023 46                   11674.0
     47                   11191.0
     48                   11464.0
     49                   11114.0
     50                   10841.0

[337 rows x 6 columns]

In [1147]:
# Delete the level 1 header :
df_onelevel = df.copy()
df_onelevel.columns = df.columns.droplevel(1)
df_onelevel

           Covid    Flu  Bronchiolitis  Pneumopathy  Total Resp. Synd.  \
Year Week
2017 26      0.0    0.0           22.0          3.0               25.0
     27      0.0    0.0           20.0          6.0               26.0
     28      0.0    0.0           18.0          2.0               20.0
     29      0.0    0.0           11.0          2.0               13.0
     30      0.0    0.0           13.0          5.0               18.0
...          ...    ...            ...          ...                ...
2023 46     78.0  100.0          327.0         31.0              536.0
     47    103.0  111.0          342.0         38.0              594.0
     48     87.0  117.0          349.0         59.0              612.0
     49    107.0  169.0          278.0         68.0              622.0
     50     99.0  182.0          255.0         54.0              590.0

           Number of consultations
Year Week
2017 26                    12958.0
     27                    12677.0
     28                     9430.0
     29                    10774.0
     30                     9297.0
...                            ...
2023 46                    11674.0
     47                    11191.0
     48                    11464.0
     49                    11114.0
     50                    10841.0

[337 rows x 6 columns]

In [1148]:
current_year = df.index[-1][0]

In [1149]:
# Remove current year to compute the baseline
df_for_baseline =df.loc[df.index.get_level_values(0) != current_year]
df_for_baseline

            Covid      Flu Bronchiolitis Pneumopathy Total Resp. Synd.  \
          current  current       current     current           current
Year Week
2017 26       0.0    0.000          22.0         3.0            25.000
     27       0.0    0.000          20.0         6.0            26.000
     28       0.0    0.000          18.0         2.0            20.000
     29       0.0    0.000          11.0         2.0            13.000
     30       0.0    0.000          13.0         5.0            18.000
...           ...      ...           ...         ...               ...
2022 48      78.0  371.000         535.0        36.0             1.020
     49      86.0  593.000         354.0        29.0             1.062
     50      73.0  959.000         219.0        24.0             1.275
     51      77.0    1.072         175.0        17.0             1.341
     52      40.0  463.000         121.0        19.0           643.000

          Number of consultations
                          current
Year Week
2017 26                   12958.0
     27                   12677.0
     28                    9430.0
     29                   10774.0
     30                    9297.0
...                           ...
2022 48                   15284.0
     49                   15389.0
     50                   14299.0
     51                   12017.0
     52                    7723.0

[287 rows x 6 columns]

In [1150]:
df_agg = df_for_baseline.groupby('Week').agg(['mean', 'std'])
df_agg = df_agg.droplevel(1, axis=1)
df_agg

           Covid                     Flu             Bronchiolitis  \
            mean         std        mean         std          mean
Week
1      84.800000  164.607715  101.400000   68.441946    109.600000
2     130.600000  249.230415  154.200000   91.688058     97.200000
3     142.200000  261.805653  235.800000  128.388862    118.200000
4     118.200000  200.142949  335.200000  202.256520    111.000000
5      84.600000  135.903642  437.400000  336.231022    128.400000
6      57.800000   79.637931  490.400000  403.606615    127.200000
7      37.000000   50.724747  411.200000  319.998750    108.800000
8      31.600000   44.388061  281.600000  223.307635     90.200000
9      30.200000   44.308013  177.600000  124.443963     85.400000
10     31.200000   44.195022  175.400000  154.757229     81.800000
11     51.800000   70.279442  232.000000  268.828012     90.600000
12     75.200000   95.003684  217.600000  334.024400    115.600000
13     82.400000   98.773984  193.600000  345.982369     91.400000
14     71.200000   89.569526  188.200000  381.378683     70.200000
15     56.800000   81.183126  154.200000  322.494496     68.800000
16     33.200000   44.437597   55.000000  112.425531     44.200000
17     29.800000   42.133122   28.000000   56.519908     31.800000
18     26.600000   33.716465   13.600000   26.005769     24.800000
19     14.200000   19.626513   14.400000   27.745270     26.800000
20     20.800000   25.508822   11.000000   18.520259     41.200000
21     17.400000   19.793938    6.600000   12.074767     39.200000
22     22.200000   23.069460    4.400000    4.979960     36.200000
23     34.800000   43.631411    4.200000    6.260990     44.000000
24     42.400000   51.032343    2.400000    4.827007     30.400000
25     34.400000   49.181297    8.000000   11.313708     37.800000
26     38.666667   54.213160    3.833333    6.997619     42.000000
27     40.666667   77.101664    5.500000   10.709809     37.833333
28     22.166667   33.361155    3.666667    3.502380     33.666667
29     15.833333   34.925158    4.833333   10.400321     29.833333
30     11.833333   20.989680    4.000000    9.316652     21.333333
31      8.833333   13.614943    1.833333    4.020779     18.000000
32      5.000000    6.511528    2.500000    5.205766      5.666667
33      8.666667   13.351654    0.166667    0.408248      6.166667
34      7.833333   11.426577    2.000000    2.529822      8.666667
35     11.000000   13.475904    1.166667    1.602082     11.166667
36     19.333333   28.814348    2.500000    4.679744     16.333333
37     33.666667   46.345082    7.833333   10.438710     45.333333
38     22.166667   25.443401    9.666667    9.136009     68.166667
39     20.333333   28.068963   13.500000   13.736812     77.333333
40     26.000000   36.600546   11.166667    9.537645     99.500000
41     26.333333   42.297360   16.833333   16.582119    130.000000
42     26.833333   42.239397   20.500000   26.643949    177.000000
43     17.166667   23.836247   18.500000   34.180404    182.666667
44     16.333333   21.491083   18.666667   31.155524    158.666667
45     22.833333   29.260326   28.166667   46.636538    184.833333
46     33.500000   42.236240   43.833333   69.222588    242.000000
47     46.333333   51.523457   77.000000  113.138853    261.000000
48     45.166667   52.878792  101.666667  138.764068    289.833333
49     52.166667   65.337330  164.500000  217.767537    283.000000
50     42.500000   47.289534  269.500000  352.218540    225.333333
51     47.166667   53.078872  152.512000  159.683242    206.666667
52     35.666667   50.945723  172.500000  166.949993    144.833333

                 Pneumopathy            Total Resp. Synd.              \
             std        mean        std              mean         std
Week
1      49.717200   10.000000   6.204837        305.800000  219.237770
2      33.663036    7.200000   3.420526        389.200000  276.230339
3      17.908099   13.800000   6.016644        510.000000  259.234450
4      14.142136    9.800000   3.271085        574.200000  200.151692
5      39.595454   14.800000   5.403702        460.604800  333.219575
6      40.201990   13.400000   6.580274        258.630600  244.722488
7      59.373395   15.000000   7.314369        572.000000  288.025173
8      41.853315   10.000000   5.431390        413.400000  176.930212
9      51.949976   13.600000   5.856620        306.800000  116.551276
10     40.233071    9.800000   2.774887        298.200000  178.226541
11     29.863021   13.000000   4.847680        387.400000  302.619894
12     78.046781   14.200000   2.863564        201.021800  164.078037
13     63.081693   10.200000   4.438468        157.820000  144.209438
14     50.266291   11.200000   5.585696        111.030000   90.076381
15     40.419055    6.600000   4.615192        286.400000  401.633290
16     24.159884    3.000000   2.549510        135.400000  160.143061
17     13.700365    3.600000   3.577709         93.200000   95.248097
18     12.833550    3.400000   2.792848         68.400000   52.590874
19     18.047160    6.800000   6.058052         62.200000   53.260680
20     26.771253    6.600000   4.979960         79.600000   61.264182
21     22.061278    6.000000   3.605551         69.200000   41.324327
22     22.331592    5.000000   3.674235         67.800000   27.462702
23     37.128156    6.400000   4.505552         89.400000   40.034985
24     20.342075    5.400000   4.449719         80.600000   46.371327
25     28.934409    5.600000   2.701851         85.800000   57.163800
26     29.536418    6.500000   5.128353         91.000000   65.884748
27     31.428755    8.000000   3.741657         92.000000   99.685505
28     27.868740    3.666667   1.966384         63.166667   53.458083
29     27.520296    3.833333   1.940790         54.333333   60.351194
30     13.544987    2.333333   2.250926         39.500000   34.192104
31      8.024961    1.666667   1.366260         30.333333   23.191953
32      4.802777    1.333333   1.505545         14.500000   14.869432
33      4.167333    0.666667   1.032796         15.666667   17.200775
34      4.966555    3.000000   2.683282         21.500000   18.185159
35      4.792355    2.000000   1.414214         25.333333   17.851237
36      5.278889    2.333333   1.211060         40.500000   37.580580
37     13.662601    5.333333   3.881580         92.166667   66.625571
38     18.486932    3.500000   2.073644        103.500000   39.429684
39     31.174776    7.833333   2.483277        119.000000   71.254474
40     49.605443   11.666667   5.163978        148.333333   91.042115
41     84.325560   12.333333   6.742897        185.500000  139.276344
42    112.292475   16.500000   9.994999        240.833333  184.494354
43    130.573606   14.500000   7.687652        232.833333  184.669886
44    129.509330   10.500000  10.232302        204.166667  175.589768
45    127.187132   10.500000   5.958188        246.333333  178.111950
46    161.122314   15.166667   6.554896        334.500000  236.021821
47    160.568988   20.333333   9.070097        404.666667  282.626019
48    155.096637   25.000000  13.160547        291.836667  208.336843
49    118.571497   26.500000  12.660964        349.343667  252.462331
50     90.192387   25.500000  10.310189        350.545833  238.010646
51     85.125006   20.333333  11.570076        381.890167  250.597367
52     65.846539   14.333333   9.584710        367.333333  179.899602

     Number of consultations
                        mean           std
Week
1               17932.200000  12436.652532
2               21696.400000  10165.271433
3               22675.600000  10324.181532
4               22409.200000  10540.503057
5               22504.000000   9828.897878
6               22799.600000   9413.704175
7               21014.600000   8643.576563
8               19634.200000   7896.410210
9               19457.600000   9222.666713
10              21176.400000  10559.452012
11              20888.600000   8744.600523
12              21123.600000  11431.527383
13              20596.000000  11924.407511
14              18834.600000   9834.474023
15              18922.600000   9521.204299
16              15890.800000   7881.790894
17              15060.000000   6851.479986
18              14673.000000   8825.759882
19              15280.800000   8072.546946
20              19896.200000   9345.741956
21              16165.200000   7497.794122
22              18850.000000   9663.387191
23              18340.400000   9179.842417
24              19630.000000  10130.354559
25              18877.200000   8214.483654
26              18664.500000   8570.051686
27              18371.500000   7620.523046
28              14588.166667   4797.635643
29              14154.833333   5684.898431
30              13400.500000   5159.743317
31              10247.666667   3132.146463
32               8506.666667   2974.236350
33               8107.833333   4462.658867
34              12485.000000   6519.959110
35              14999.666667   6021.845786
36              18296.500000   8394.311401
37              20486.666667  10899.574408
38              20755.333333  10141.551610
39              20805.500000  10268.886147
40              19955.833333   9151.008937
41              20752.833333   9942.015639
42              22086.000000  10177.764096
43              18719.000000   8122.012731
44              14609.000000   7589.365323
45              19486.000000   9362.151526
46              20141.833333   8007.220627
47              22380.166667   9703.567126
48              22219.166667   9890.758624
49              22793.333333   9522.304210
50              22649.666667   9814.013769
51              20843.500000   9249.767667
52              12008.500000   5662.405734

In [1151]:
# Compute the 95% confidence interval corresponding to the mean and std in each row 
# Number of years of data
df_agg['Covid', 'lower'] = df_agg['Covid', 'mean'] - df_agg['Covid', 'std']
df_agg['Covid', 'upper'] = df_agg['Covid', 'mean'] + df_agg['Covid', 'std']
df_agg[('Flu', 'lower')] = df_agg[('Flu', 'mean')] -df_agg[('Flu', 'std')] 
df_agg[('Flu', 'upper')] = df_agg[('Flu', 'mean')] +df_agg[('Flu', 'std')] 
df_agg[('Bronchiolitis', 'lower')] = df_agg[('Bronchiolitis', 'mean')] -df_agg[('Bronchiolitis', 'std')] 
df_agg[('Bronchiolitis', 'upper')] = df_agg[('Bronchiolitis', 'mean')] +df_agg[('Bronchiolitis', 'std')] 
df_agg[('Pneumopathy', 'lower')] = df_agg[('Pneumopathy', 'mean')] -df_agg[('Pneumopathy', 'std')] 
df_agg[('Pneumopathy', 'upper')] = df_agg[('Pneumopathy', 'mean')] +df_agg[('Pneumopathy', 'std')] 
df_agg[('Total Resp. Synd.', 'lower')] = df_agg[('Total Resp. Synd.', 'mean')] -df_agg[('Total Resp. Synd.', 'std')] 
df_agg[('Total Resp. Synd.', 'upper')] = df_agg[('Total Resp. Synd.', 'mean')] +df_agg[('Total Resp. Synd.', 'std')] 
df_agg[('Number of consultations', 'lower')] = df_agg['Number of consultations']['mean'] - df_agg['Number of consultations']['std']
df_agg[('Number of consultations', 'upper')] = df_agg['Number of consultations']['mean'] - df_agg['Number of consultations']['std']
# Remove all the columns corresponding to the standard deviation

df_agg = df_agg[[('Covid', 'mean'), ('Covid', 'lower'),('Covid', 'upper'), ('Flu', 'mean'), ('Flu', 'lower'), ('Flu', 'upper'), ('Bronchiolitis', 'mean'), ('Bronchiolitis', 'lower'), ('Bronchiolitis', 'upper'), ('Pneumopathy', 'mean'), ('Pneumopathy', 'lower'), ('Pneumopathy', 'upper'), ('Total Resp. Synd.', 'mean'), ('Total Resp. Synd.', 'lower'), ('Total Resp. Synd.', 'upper'), ('Number of consultations', 'mean'), ('Number of consultations', 'lower'), ('Number of consultations', 'upper')]]

In [1152]:
df_agg

           Covid                                 Flu                          \
            mean       lower       upper        mean       lower       upper
Week
1      84.800000  -79.807715  249.407715  101.400000   32.958054  169.841946
2     130.600000 -118.630415  379.830415  154.200000   62.511942  245.888058
3     142.200000 -119.605653  404.005653  235.800000  107.411138  364.188862
4     118.200000  -81.942949  318.342949  335.200000  132.943480  537.456520
5      84.600000  -51.303642  220.503642  437.400000  101.168978  773.631022
6      57.800000  -21.837931  137.437931  490.400000   86.793385  894.006615
7      37.000000  -13.724747   87.724747  411.200000   91.201250  731.198750
8      31.600000  -12.788061   75.988061  281.600000   58.292365  504.907635
9      30.200000  -14.108013   74.508013  177.600000   53.156037  302.043963
10     31.200000  -12.995022   75.395022  175.400000   20.642771  330.157229
11     51.800000  -18.479442  122.079442  232.000000  -36.828012  500.828012
12     75.200000  -19.803684  170.203684  217.600000 -116.424400  551.624400
13     82.400000  -16.373984  181.173984  193.600000 -152.382369  539.582369
14     71.200000  -18.369526  160.769526  188.200000 -193.178683  569.578683
15     56.800000  -24.383126  137.983126  154.200000 -168.294496  476.694496
16     33.200000  -11.237597   77.637597   55.000000  -57.425531  167.425531
17     29.800000  -12.333122   71.933122   28.000000  -28.519908   84.519908
18     26.600000   -7.116465   60.316465   13.600000  -12.405769   39.605769
19     14.200000   -5.426513   33.826513   14.400000  -13.345270   42.145270
20     20.800000   -4.708822   46.308822   11.000000   -7.520259   29.520259
21     17.400000   -2.393938   37.193938    6.600000   -5.474767   18.674767
22     22.200000   -0.869460   45.269460    4.400000   -0.579960    9.379960
23     34.800000   -8.831411   78.431411    4.200000   -2.060990   10.460990
24     42.400000   -8.632343   93.432343    2.400000   -2.427007    7.227007
25     34.400000  -14.781297   83.581297    8.000000   -3.313708   19.313708
26     38.666667  -15.546493   92.879826    3.833333   -3.164285   10.830952
27     40.666667  -36.434998  117.768331    5.500000   -5.209809   16.209809
28     22.166667  -11.194488   55.527822    3.666667    0.164287    7.169047
29     15.833333  -19.091825   50.758491    4.833333   -5.566987   15.233654
30     11.833333   -9.156347   32.823013    4.000000   -5.316652   13.316652
31      8.833333   -4.781609   22.448276    1.833333   -2.187446    5.854113
32      5.000000   -1.511528   11.511528    2.500000   -2.705766    7.705766
33      8.666667   -4.684987   22.018321    0.166667   -0.241582    0.574915
34      7.833333   -3.593244   19.259911    2.000000   -0.529822    4.529822
35     11.000000   -2.475904   24.475904    1.166667   -0.435415    2.768749
36     19.333333   -9.481015   48.147682    2.500000   -2.179744    7.179744
37     33.666667  -12.678416   80.011749    7.833333   -2.605377   18.272043
38     22.166667   -3.276735   47.610068    9.666667    0.530657   18.802676
39     20.333333   -7.735629   48.402296   13.500000   -0.236812   27.236812
40     26.000000  -10.600546   62.600546   11.166667    1.629022   20.704311
41     26.333333  -15.964027   68.630693   16.833333    0.251214   33.415452
42     26.833333  -15.406064   69.072730   20.500000   -6.143949   47.143949
43     17.166667   -6.669580   41.002914   18.500000  -15.680404   52.680404
44     16.333333   -5.157750   37.824417   18.666667  -12.488857   49.822191
45     22.833333   -6.426992   52.093659   28.166667  -18.469871   74.803205
46     33.500000   -8.736240   75.736240   43.833333  -25.389255  113.055921
47     46.333333   -5.190124   97.856791   77.000000  -36.138853  190.138853
48     45.166667   -7.712126   98.045459  101.666667  -37.097402  240.430735
49     52.166667  -13.170663  117.503996  164.500000  -53.267537  382.267537
50     42.500000   -4.789534   89.789534  269.500000  -82.718540  621.718540
51     47.166667   -5.912205  100.245539  152.512000   -7.171242  312.195242
52     35.666667  -15.279056   86.612389  172.500000    5.550007  339.449993

     Bronchiolitis                         Pneumopathy                        \
              mean       lower       upper        mean      lower      upper
Week
1       109.600000   59.882800  159.317200   10.000000   3.795163  16.204837
2        97.200000   63.536964  130.863036    7.200000   3.779474  10.620526
3       118.200000  100.291901  136.108099   13.800000   7.783356  19.816644
4       111.000000   96.857864  125.142136    9.800000   6.528915  13.071085
5       128.400000   88.804546  167.995454   14.800000   9.396298  20.203702
6       127.200000   86.998010  167.401990   13.400000   6.819726  19.980274
7       108.800000   49.426605  168.173395   15.000000   7.685631  22.314369
8        90.200000   48.346685  132.053315   10.000000   4.568610  15.431390
9        85.400000   33.450024  137.349976   13.600000   7.743380  19.456620
10       81.800000   41.566929  122.033071    9.800000   7.025113  12.574887
11       90.600000   60.736979  120.463021   13.000000   8.152320  17.847680
12      115.600000   37.553219  193.646781   14.200000  11.336436  17.063564
13       91.400000   28.318307  154.481693   10.200000   5.761532  14.638468
14       70.200000   19.933709  120.466291   11.200000   5.614304  16.785696
15       68.800000   28.380945  109.219055    6.600000   1.984808  11.215192
16       44.200000   20.040116   68.359884    3.000000   0.450490   5.549510
17       31.800000   18.099635   45.500365    3.600000   0.022291   7.177709
18       24.800000   11.966450   37.633550    3.400000   0.607152   6.192848
19       26.800000    8.752840   44.847160    6.800000   0.741948  12.858052
20       41.200000   14.428747   67.971253    6.600000   1.620040  11.579960
21       39.200000   17.138722   61.261278    6.000000   2.394449   9.605551
22       36.200000   13.868408   58.531592    5.000000   1.325765   8.674235
23       44.000000    6.871844   81.128156    6.400000   1.894448  10.905552
24       30.400000   10.057925   50.742075    5.400000   0.950281   9.849719
25       37.800000    8.865591   66.734409    5.600000   2.898149   8.301851
26       42.000000   12.463582   71.536418    6.500000   1.371647  11.628353
27       37.833333    6.404578   69.262089    8.000000   4.258343  11.741657
28       33.666667    5.797927   61.535407    3.666667   1.700283   5.633051
29       29.833333    2.313038   57.353629    3.833333   1.892543   5.774124
30       21.333333    7.788347   34.878320    2.333333   0.082408   4.584259
31       18.000000    9.975039   26.024961    1.666667   0.300407   3.032927
32        5.666667    0.863890   10.469444    1.333333  -0.172212   2.838879
33        6.166667    1.999333   10.334000    0.666667  -0.366129   1.699462
34        8.666667    3.700112   13.633221    3.000000   0.316718   5.683282
35       11.166667    6.374312   15.959022    2.000000   0.585786   3.414214
36       16.333333   11.054445   21.612222    2.333333   1.122273   3.544393
37       45.333333   31.670732   58.995934    5.333333   1.451753   9.214914
38       68.166667   49.679734   86.653599    3.500000   1.426356   5.573644
39       77.333333   46.158557  108.508109    7.833333   5.350056  10.316611
40       99.500000   49.894557  149.105443   11.666667   6.502689  16.830644
41      130.000000   45.674440  214.325560   12.333333   5.590436  19.076231
42      177.000000   64.707525  289.292475   16.500000   6.505001  26.494999
43      182.666667   52.093060  313.240273   14.500000   6.812348  22.187652
44      158.666667   29.157336  288.175997   10.500000   0.267698  20.732302
45      184.833333   57.646201  312.020466   10.500000   4.541812  16.458188
46      242.000000   80.877686  403.122314   15.166667   8.611770  21.721563
47      261.000000  100.431012  421.568988   20.333333  11.263236  29.403431
48      289.833333  134.736697  444.929970   25.000000  11.839453  38.160547
49      283.000000  164.428503  401.571497   26.500000  13.839036  39.160964
50      225.333333  135.140946  315.525720   25.500000  15.189811  35.810189
51      206.666667  121.541661  291.791673   20.333333   8.763257  31.903410
52      144.833333   78.986795  210.679872   14.333333   4.748623  23.918043

     Total Resp. Synd.                         Number of consultations  \
                  mean       lower       upper                    mean
Week
1           305.800000   86.562230  525.037770            17932.200000
2           389.200000  112.969661  665.430339            21696.400000
3           510.000000  250.765550  769.234450            22675.600000
4           574.200000  374.048308  774.351692            22409.200000
5           460.604800  127.385225  793.824375            22504.000000
6           258.630600   13.908112  503.353088            22799.600000
7           572.000000  283.974827  860.025173            21014.600000
8           413.400000  236.469788  590.330212            19634.200000
9           306.800000  190.248724  423.351276            19457.600000
10          298.200000  119.973459  476.426541            21176.400000
11          387.400000   84.780106  690.019894            20888.600000
12          201.021800   36.943763  365.099837            21123.600000
13          157.820000   13.610562  302.029438            20596.000000
14          111.030000   20.953619  201.106381            18834.600000
15          286.400000 -115.233290  688.033290            18922.600000
16          135.400000  -24.743061  295.543061            15890.800000
17           93.200000   -2.048097  188.448097            15060.000000
18           68.400000   15.809126  120.990874            14673.000000
19           62.200000    8.939320  115.460680            15280.800000
20           79.600000   18.335818  140.864182            19896.200000
21           69.200000   27.875673  110.524327            16165.200000
22           67.800000   40.337298   95.262702            18850.000000
23           89.400000   49.365015  129.434985            18340.400000
24           80.600000   34.228673  126.971327            19630.000000
25           85.800000   28.636200  142.963800            18877.200000
26           91.000000   25.115252  156.884748            18664.500000
27           92.000000   -7.685505  191.685505            18371.500000
28           63.166667    9.708583  116.624750            14588.166667
29           54.333333   -6.017861  114.684528            14154.833333
30           39.500000    5.307896   73.692104            13400.500000
31           30.333333    7.141381   53.525286            10247.666667
32           14.500000   -0.369432   29.369432             8506.666667
33           15.666667   -1.534109   32.867442             8107.833333
34           21.500000    3.314841   39.685159            12485.000000
35           25.333333    7.482096   43.184570            14999.666667
36           40.500000    2.919420   78.080580            18296.500000
37           92.166667   25.541096  158.792237            20486.666667
38          103.500000   64.070316  142.929684            20755.333333
39          119.000000   47.745526  190.254474            20805.500000
40          148.333333   57.291219  239.375448            19955.833333
41          185.500000   46.223656  324.776344            20752.833333
42          240.833333   56.338979  425.327687            22086.000000
43          232.833333   48.163448  417.503219            18719.000000
44          204.166667   28.576899  379.756435            14609.000000
45          246.333333   68.221384  424.445283            19486.000000
46          334.500000   98.478179  570.521821            20141.833333
47          404.666667  122.040648  687.292686            22380.166667
48          291.836667   83.499824  500.173509            22219.166667
49          349.343667   96.881336  601.805998            22793.333333
50          350.545833  112.535187  588.556479            22649.666667
51          381.890167  131.292800  632.487534            20843.500000
52          367.333333  187.433732  547.232935            12008.500000


             lower         upper
Week
1      5495.547468   5495.547468
2     11531.128567  11531.128567
3     12351.418468  12351.418468
4     11868.696943  11868.696943
5     12675.102122  12675.102122
6     13385.895825  13385.895825
7     12371.023437  12371.023437
8     11737.789790  11737.789790
9     10234.933287  10234.933287
10    10616.947988  10616.947988
11    12143.999477  12143.999477
12     9692.072617   9692.072617
13     8671.592489   8671.592489
14     9000.125977   9000.125977
15     9401.395701   9401.395701
16     8009.009106   8009.009106
17     8208.520014   8208.520014
18     5847.240118   5847.240118
19     7208.253054   7208.253054
20    10550.458044  10550.458044
21     8667.405878   8667.405878
22     9186.612809   9186.612809
23     9160.557583   9160.557583
24     9499.645441   9499.645441
25    10662.716346  10662.716346
26    10094.448314  10094.448314
27    10750.976954  10750.976954
28     9790.531023   9790.531023
29     8469.934903   8469.934903
30     8240.756683   8240.756683
31     7115.520204   7115.520204
32     5532.430316   5532.430316
33     3645.174466   3645.174466
34     5965.040890   5965.040890
35     8977.820881   8977.820881
36     9902.188599   9902.188599
37     9587.092259   9587.092259
38    10613.781723  10613.781723
39    10536.613853  10536.613853
40    10804.824396  10804.824396
41    10810.817694  10810.817694
42    11908.235904  11908.235904
43    10596.987269  10596.987269
44     7019.634677   7019.634677
45    10123.848474  10123.848474
46    12134.612707  12134.612707
47    12676.599541  12676.599541
48    12328.408042  12328.408042
49    13271.029123  13271.029123
50    12835.652897  12835.652897
51    11593.732333  11593.732333
52     6346.094266   6346.094266

In [1153]:
df

            Covid     Flu Bronchiolitis Pneumopathy Total Resp. Synd.  \
          current current       current     current           current
Year Week
2017 26       0.0     0.0          22.0         3.0              25.0
     27       0.0     0.0          20.0         6.0              26.0
     28       0.0     0.0          18.0         2.0              20.0
     29       0.0     0.0          11.0         2.0              13.0
     30       0.0     0.0          13.0         5.0              18.0
...           ...     ...           ...         ...               ...
2023 46      78.0   100.0         327.0        31.0             536.0
     47     103.0   111.0         342.0        38.0             594.0
     48      87.0   117.0         349.0        59.0             612.0
     49     107.0   169.0         278.0        68.0             622.0
     50      99.0   182.0         255.0        54.0             590.0

          Number of consultations
                          current
Year Week
2017 26                   12958.0
     27                   12677.0
     28                    9430.0
     29                   10774.0
     30                    9297.0
...                           ...
2023 46                   11674.0
     47                   11191.0
     48                   11464.0
     49                   11114.0
     50                   10841.0

[337 rows x 6 columns]

In [1154]:
# Merge dataframes on the 'week' column
df_agg.reset_index(inplace=True)
df.reset_index(inplace=True)
result_df = pd.merge(df, df_agg, on= 'Week' , how='inner')
result_df.set_index(['Year', 'Week'], inplace=True)
# Sort by year and week
result_df.sort_index(inplace=True)
result_df

C:\Users\tfauvel\AppData\Local\Temp\ipykernel_9872\3791642749.py:4: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  result_df = pd.merge(df, df_agg, on= 'Week' , how='inner')

            Covid     Flu Bronchiolitis Pneumopathy Total Resp. Synd.  \
          current current       current     current           current
Year Week
2017 26       0.0     0.0          22.0         3.0              25.0
     27       0.0     0.0          20.0         6.0              26.0
     28       0.0     0.0          18.0         2.0              20.0
     29       0.0     0.0          11.0         2.0              13.0
     30       0.0     0.0          13.0         5.0              18.0
...           ...     ...           ...         ...               ...
2023 46      78.0   100.0         327.0        31.0             536.0
     47     103.0   111.0         342.0        38.0             594.0
     48      87.0   117.0         349.0        59.0             612.0
     49     107.0   169.0         278.0        68.0             622.0
     50      99.0   182.0         255.0        54.0             590.0

          Number of consultations      Covid                         \
                          current       mean      lower       upper
Year Week
2017 26                   12958.0  38.666667 -15.546493   92.879826
     27                   12677.0  40.666667 -36.434998  117.768331
     28                    9430.0  22.166667 -11.194488   55.527822
     29                   10774.0  15.833333 -19.091825   50.758491
     30                    9297.0  11.833333  -9.156347   32.823013
...                           ...        ...        ...         ...
2023 46                   11674.0  33.500000  -8.736240   75.736240
     47                   11191.0  46.333333  -5.190124   97.856791
     48                   11464.0  45.166667  -7.712126   98.045459
     49                   11114.0  52.166667 -13.170663  117.503996
     50                   10841.0  42.500000  -4.789534   89.789534

                  Flu  ... Bronchiolitis Pneumopathy                        \
                 mean  ...         upper        mean      lower      upper
Year Week              ...
2017 26      3.833333  ...     71.536418    6.500000   1.371647  11.628353
     27      5.500000  ...     69.262089    8.000000   4.258343  11.741657
     28      3.666667  ...     61.535407    3.666667   1.700283   5.633051
     29      4.833333  ...     57.353629    3.833333   1.892543   5.774124
     30      4.000000  ...     34.878320    2.333333   0.082408   4.584259
...               ...  ...           ...         ...        ...        ...
2023 46     43.833333  ...    403.122314   15.166667   8.611770  21.721563
     47     77.000000  ...    421.568988   20.333333  11.263236  29.403431
     48    101.666667  ...    444.929970   25.000000  11.839453  38.160547
     49    164.500000  ...    401.571497   26.500000  13.839036  39.160964
     50    269.500000  ...    315.525720   25.500000  15.189811  35.810189

          Total Resp. Synd.                         Number of consultations  \
                       mean       lower       upper                    mean
Year Week
2017 26           91.000000   25.115252  156.884748            18664.500000
     27           92.000000   -7.685505  191.685505            18371.500000
     28           63.166667    9.708583  116.624750            14588.166667
     29           54.333333   -6.017861  114.684528            14154.833333
     30           39.500000    5.307896   73.692104            13400.500000
...                     ...         ...         ...                     ...
2023 46          334.500000   98.478179  570.521821            20141.833333
     47          404.666667  122.040648  687.292686            22380.166667
     48          291.836667   83.499824  500.173509            22219.166667
     49          349.343667   96.881336  601.805998            22793.333333
     50          350.545833  112.535187  588.556479            22649.666667


                  lower         upper
Year Week
2017 26    10094.448314  10094.448314
     27    10750.976954  10750.976954
     28     9790.531023   9790.531023
     29     8469.934903   8469.934903
     30     8240.756683   8240.756683
...                 ...           ...
2023 46    12134.612707  12134.612707
     47    12676.599541  12676.599541
     48    12328.408042  12328.408042
     49    13271.029123  13271.029123
     50    12835.652897  12835.652897

[337 rows x 24 columns]

In [1155]:
# Create, for each disease, an "alert" column that is True if the number of cases is above the upper confidence interval and False otherwise
result_df[('Covid', 'alert')] = result_df[('Covid', 'current')] > result_df[('Covid', 'upper')]
result_df[('Flu', 'alert')] = result_df[('Flu', 'current')] > result_df[('Flu', 'upper')]
result_df[('Bronchiolitis', 'alert')] = result_df[('Bronchiolitis', 'current')] > result_df[('Bronchiolitis', 'upper')]
result_df[('Pneumopathy', 'alert')] = result_df[('Pneumopathy', 'current')] > result_df[('Pneumopathy', 'upper')]
result_df[('Total Resp. Synd.', 'alert')] = result_df[('Total Resp. Synd.', 'current')] > result_df[('Total Resp. Synd.', 'upper')]
# Same for the number of consultations
result_df[('Number of consultations', 'alert')] = result_df[('Number of consultations', 'current')] > result_df[('Number of consultations', 'upper')]

result_df

            Covid     Flu Bronchiolitis Pneumopathy Total Resp. Synd.  \
          current current       current     current           current
Year Week
2017 26       0.0     0.0          22.0         3.0              25.0
     27       0.0     0.0          20.0         6.0              26.0
     28       0.0     0.0          18.0         2.0              20.0
     29       0.0     0.0          11.0         2.0              13.0
     30       0.0     0.0          13.0         5.0              18.0
...           ...     ...           ...         ...               ...
2023 46      78.0   100.0         327.0        31.0             536.0
     47     103.0   111.0         342.0        38.0             594.0
     48      87.0   117.0         349.0        59.0             612.0
     49     107.0   169.0         278.0        68.0             622.0
     50      99.0   182.0         255.0        54.0             590.0

          Number of consultations      Covid                         \
                          current       mean      lower       upper
Year Week
2017 26                   12958.0  38.666667 -15.546493   92.879826
     27                   12677.0  40.666667 -36.434998  117.768331
     28                    9430.0  22.166667 -11.194488   55.527822
     29                   10774.0  15.833333 -19.091825   50.758491
     30                    9297.0  11.833333  -9.156347   32.823013
...                           ...        ...        ...         ...
2023 46                   11674.0  33.500000  -8.736240   75.736240
     47                   11191.0  46.333333  -5.190124   97.856791
     48                   11464.0  45.166667  -7.712126   98.045459
     49                   11114.0  52.166667 -13.170663  117.503996
     50                   10841.0  42.500000  -4.789534   89.789534

                  Flu  ... Total Resp. Synd. Number of consultations  \
                 mean  ...             upper                    mean
Year Week              ...
2017 26      3.833333  ...        156.884748            18664.500000
     27      5.500000  ...        191.685505            18371.500000
     28      3.666667  ...        116.624750            14588.166667
     29      4.833333  ...        114.684528            14154.833333
     30      4.000000  ...         73.692104            13400.500000
...               ...  ...               ...                     ...
2023 46     43.833333  ...        570.521821            20141.833333
     47     77.000000  ...        687.292686            22380.166667
     48    101.666667  ...        500.173509            22219.166667
     49    164.500000  ...        601.805998            22793.333333
     50    269.500000  ...        588.556479            22649.666667

                                       Covid    Flu Bronchiolitis Pneumopathy  \
                  lower         upper  alert  alert         alert       alert
Year Week
2017 26    10094.448314  10094.448314  False  False         False       False
     27    10750.976954  10750.976954  False  False         False       False
     28     9790.531023   9790.531023  False  False         False       False
     29     8469.934903   8469.934903  False  False         False       False
     30     8240.756683   8240.756683  False  False         False        True
...                 ...           ...    ...    ...           ...         ...
2023 46    12134.612707  12134.612707   True  False         False        True
     47    12676.599541  12676.599541   True  False         False        True
     48    12328.408042  12328.408042  False  False         False        True
     49    13271.029123  13271.029123  False  False         False        True
     50    12835.652897  12835.652897   True  False         False        True

          Total Resp. Synd. Number of consultations
                      alert                   alert
Year Week
2017 26               False                    True
     27               False                    True
     28               False                   False
     29               False                    True
     30               False                    True
...                     ...                     ...
2023 46               False                   False
     47               False                   False
     48                True                   False
     49                True                   False
     50                True                   False

[337 rows x 30 columns]

In [1156]:
# Sort the level 1 headers according to the level 0 header
result_df.sort_index(axis=1, level=0, inplace=True)
result_df

          Bronchiolitis                                              Covid  \
                  alert current       lower        mean       upper  alert
Year Week
2017 26           False    22.0   12.463582   42.000000   71.536418  False
     27           False    20.0    6.404578   37.833333   69.262089  False
     28           False    18.0    5.797927   33.666667   61.535407  False
     29           False    11.0    2.313038   29.833333   57.353629  False
     30           False    13.0    7.788347   21.333333   34.878320  False
...                 ...     ...         ...         ...         ...    ...
2023 46           False   327.0   80.877686  242.000000  403.122314   True
     47           False   342.0  100.431012  261.000000  421.568988   True
     48           False   349.0  134.736697  289.833333  444.929970  False
     49           False   278.0  164.428503  283.000000  401.571497  False
     50           False   255.0  135.140946  225.333333  315.525720   True

                                                     ... Pneumopathy          \
          current      lower       mean       upper  ...       alert current
Year Week                                            ...
2017 26       0.0 -15.546493  38.666667   92.879826  ...       False     3.0
     27       0.0 -36.434998  40.666667  117.768331  ...       False     6.0
     28       0.0 -11.194488  22.166667   55.527822  ...       False     2.0
     29       0.0 -19.091825  15.833333   50.758491  ...       False     2.0
     30       0.0  -9.156347  11.833333   32.823013  ...        True     5.0
...           ...        ...        ...         ...  ...         ...     ...
2023 46      78.0  -8.736240  33.500000   75.736240  ...        True    31.0
     47     103.0  -5.190124  46.333333   97.856791  ...        True    38.0
     48      87.0  -7.712126  45.166667   98.045459  ...        True    59.0
     49     107.0 -13.170663  52.166667  117.503996  ...        True    68.0
     50      99.0  -4.789534  42.500000   89.789534  ...        True    54.0

                                           Total Resp. Synd.          \
               lower       mean      upper             alert current
Year Week
2017 26     1.371647   6.500000  11.628353             False    25.0
     27     4.258343   8.000000  11.741657             False    26.0
     28     1.700283   3.666667   5.633051             False    20.0
     29     1.892543   3.833333   5.774124             False    13.0
     30     0.082408   2.333333   4.584259             False    18.0
...              ...        ...        ...               ...     ...
2023 46     8.611770  15.166667  21.721563             False   536.0
     47    11.263236  20.333333  29.403431             False   594.0
     48    11.839453  25.000000  38.160547              True   612.0
     49    13.839036  26.500000  39.160964              True   622.0
     50    15.189811  25.500000  35.810189              True   590.0


                lower        mean       upper
Year Week
2017 26     25.115252   91.000000  156.884748
     27     -7.685505   92.000000  191.685505
     28      9.708583   63.166667  116.624750
     29     -6.017861   54.333333  114.684528
     30      5.307896   39.500000   73.692104
...               ...         ...         ...
2023 46     98.478179  334.500000  570.521821
     47    122.040648  404.666667  687.292686
     48     83.499824  291.836667  500.173509
     49     96.881336  349.343667  601.805998
     50    112.535187  350.545833  588.556479

[337 rows x 30 columns]

In [1157]:
result_df.columns

MultiIndex([(          'Bronchiolitis',   'alert'),
            (          'Bronchiolitis', 'current'),
            (          'Bronchiolitis',   'lower'),
            (          'Bronchiolitis',    'mean'),
            (          'Bronchiolitis',   'upper'),
            (                  'Covid',   'alert'),
            (                  'Covid', 'current'),
            (                  'Covid',   'lower'),
            (                  'Covid',    'mean'),
            (                  'Covid',   'upper'),
            (                    'Flu',   'alert'),
            (                    'Flu', 'current'),
            (                    'Flu',   'lower'),
            (                    'Flu',    'mean'),
            (                    'Flu',   'upper'),
            ('Number of consultations',   'alert'),
            ('Number of consultations', 'current'),
            ('Number of consultations',   'lower'),
            ('Number of consultations',    'mean'),
            ('Number of consultations',   'upper'),
            (            'Pneumopathy',   'alert'),
            (            'Pneumopathy', 'current'),
            (            'Pneumopathy',   'lower'),
            (            'Pneumopathy',    'mean'),
            (            'Pneumopathy',   'upper'),
            (      'Total Resp. Synd.',   'alert'),
            (      'Total Resp. Synd.', 'current'),
            (      'Total Resp. Synd.',   'lower'),
            (      'Total Resp. Synd.',    'mean'),
            (      'Total Resp. Synd.',   'upper')],
           )